name: Nifty Chain Scraper

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright pytz
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: python download_nifty.py

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git fetch origin main
          git checkout main
          git pull --rebase origin main

          git add nifty_chain/*
          if ! git diff --cached --quiet; then
            git commit -m "Auto update: Nifty chain snapshot [skip ci]"
            git push origin main
          else
            echo "No changes to commit."
