name: Nifty Chain Scraper

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write  # Ensure push permission

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run scraper
        run: python download_nifty.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          # Create a proper local branch
          git checkout -B main

          # Stage changes
          git add nifty_chain/*
          git diff --cached --quiet || git commit -m "Auto update: Nifty chain HTML [skip ci]"

          # Sync with remote history
          git fetch origin main
          git rebase origin/main

          # Push safely
          git push origin main --force-with-lease
